const SET_ACTIVE_FORMITEM = 'SET_ACTIVE_FORMITEM';
// const FORM_ITEM_DATA = 'FORM_ITEM_DATA';
const INIT_DRAG = 'INIT_DRAG';
const DRAG_FORMITEM_DATA = 'DRAG_FORMITEM_DATA';
const DROP_FORMITEM_DATA = 'DROP_FORMITEM_DATA';
export {
  SET_ACTIVE_FORMITEM,
  // FORM_ITEM_DATA,
  INIT_DRAG,
  DRAG_FORMITEM_DATA,
  DROP_FORMITEM_DATA
}